name: Test with Podman

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - run: podman build -t hono-saas-starter .

      - run: podman run -d -p 3000:3000 hono-saas-starter

      - name: Run the health check validation
        run: while ! curl -s 'http://localhost:3000/health' | grep 'OK'; do sleep 1; done
        timeout-minutes: 3
